#include <vector>
#include <iostream>
#include <tuple>

using namespace std;
typedef unsigned long long ull;

constexpr ull modulo = 1000000007;

vector<vector<ull>> mult_matr(const vector<vector<ull>>& A, const vector<vector<ull>>& B) {
    vector C (26, vector (26, 0ull));
    for (size_t row_A = 0; row_A < 26; row_A++) {
        for (size_t col_A1 = 0; col_A1 < 26; col_A1++) {
            const auto temp = A[row_A][col_A1];
            for (size_t col_A2 = 0; col_A2 < 26; col_A2++) {
                C[row_A][col_A2] = (C[row_A][col_A2] + temp*B[col_A1][col_A2]) % modulo;
            }
        }
    }
    return C;
}


void displayMatrix(const std::vector<std::vector<ull>>& matrix) {
    for (const auto& row : matrix) {
        for (auto& val : row) {
            std::cout << val << " ";
        }
        std::cout << "\n";
    }
}


int lengthAfterTransformations(const string& s, int t, const vector<int>& nums) {

    vector<ull> freq (26, 0);


    ull result = 0;
    vector A (26, vector (26, 0ull));
    vector Y (26, vector (26, 0ull));

    for (auto& lett: s) ++freq[lett - 'a'];

    for (size_t ind_i = 0; ind_i < 26; ind_i++) {

        for (size_t ind_j = 1; ind_j <= nums[ind_i] ; ind_j++) {
            ++A[ind_i][(ind_j+ind_i)%26];
        }
    }

    for (size_t ind_i  = 0; ind_i < 26; ind_i++)
        Y[ind_i][ind_i] = 1;



    while (t != 0) {
        if (t % 2 == 1) {
            Y = mult_matr(Y, A);
        }
        A = mult_matr(A, A);
        t /= 2;
    }

    // displayMatrix(A);
    for (size_t ind_i = 0; ind_i < 26; ind_i++)
        for (size_t ind_j = 0; ind_j < 26; ind_j++)
            result = (result + Y[ind_j][ind_i]*freq[ind_j]) % modulo;


    return  static_cast<int>(result);
}




int main() {

    const vector<tuple<string, int, vector<int>>> tests {
        // {"abcyy", 2, {1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2}},
        {"abcyydasddfhhmhghjltuirtxcbcvnjjlioixzcqwerweytyiuccnxvwaawrcvbnbnmii", 20, {4,3,10,6,13,18,17,10,12,1,1,1,1,9,1,1,6,5,3,1,1,1,1,1,1,2}}
        // {"abcyy", 1000000000, {25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25}},
        // {"bvqbowlhpfhpaddcegzxiawnprkhbvqlmqegsydbykdrxywxvtjlqkuvzasrfdwgepgkbcsxebrkeegttxugleyzytnfpsjimuxqjpjgqbxtbrpntxgxaahldwwnemzwtpgnbvhqikibmqwkxjlvklnuidgwhrxdnwjzxgazfckirtzzwacsvinisjzjyaibwamcbjkcxkdzripdrgyeewkpgofezpcbjbpbdhzltzmqffaqrqcefjwyuyimzpftumzdkazbkijezidrcabvfiltkxzzyywxogsccxkmihqwmehuicpolzxxqvyjdtsuohwthzmigprfjooframjuckvqxjboowpmbdwokzprniwejbbbzwvspufgilhylgukfqgdkiuezvfhxsbpkorbouyqapbwlbezukjhbiiykncopskkzajggslrplccqqcnogvhzjprfyuanmuuwhbndkmasesrpgwdgjyvcscmtiwyhsexvahitchwswafbftffrfpnwepijdmxlzihsnszpjvztxjvxbcbepbfhzcvmxfdibhycvzmzsnqtowvnyqoprmlpfdemyxawlahnlyihrkauraudjvkbsovqhpfvuxletqienvlcwnwdntusvwrgmlaibacdmxwarakxiqiqaaihtnfdmkrtknqrhhsebeizjwrdavzldafamwkjvtavitzoyzwavorvcbclapuzeeigndagdbpbxnexumoshtbkzlhsqetyzqfhswuxnxtrmzjaxlzjsdmdhgpjtdoogehkcanyylfsgpceosbeokdzarlogagljrzadttgwaksswbakodwjtpysrhthgmlpjixcxrfgaqcnqlchanwivxngtorsrplqmrxmaqwairjmbepggtuajfmqtbrcgczlogwkrjzhiqdbqbrcrlpovgspnmuxdqewqlbhzchfxrcxblhoozxmasnmzelzzfclsklpxexzmnenoigazshmhwkfrlkbkyerupbgedosfmvdburuqfydstnjyjpmusnfokoyjvdgnphvotckwvageasfrsknnxnbvmqqlvtyvbgijndosppsfrbzmkkgzzufzecmyqnacfyuylrewbuybecszxxovsflslzbbpapzywgahkqohvlzdgeveoqjvawwehecdlgtnseubafazduxgwbxqzponpizvsjosjddwajtpvenwbsgtqtessiacspjiehlqvjhugextkjlhgfkqiseqjhfvkewugmmwksrlxrvnrmstlklaytbqwfvzaebkbwjsqfgvwdoorepxcxbelvaobjgtdjlvqyninoehfroviegdyiilrpewvgpdipfqlizzxzzfvhqizrdcgmpbjffljpzyljupwenvybbvcgwvgqnfcfdfjlckioxkwnqiurpodtduitawsinvtbfnhbmozwukjqapeewivqmtjuqtlwygzfujfovvabmwsmmousfvcmoedejhurbxrzbdrreqymtuqzyjojjncibhelurkwajdfvdmeiabxfaqqpiqishborzzkztsfskfbbqwwathksdbrvzfbncxkmretflmddtoyxthwibtfeeowiippwoccnmpcswoqstmjdesxkhriqhftdojbsghfudrutzgduxdnrrheksjdyzrdtbkdbcrjkfhlfkvuadhiqbpnqljrqprdwmthcgstakkrmhivuirdvmwqkswjgnmqcqziwqbqxhrhhbtgagbdibjilhzuhglolxwpfywltxqfvbbvkmgpasvxaforlbgkttrnmhszehynywnwbxkshrajhymvgexcsqcfmnhiyikmzkwxtwaebajwoxeqmehyqrxyairhlsbazvkdbqhebtovualatufvauqeczcrrkyletfobzjvcauvnunnzogkdznfwstrkoicafynnbbdlutkeauqwyhqrdkgtrdbngeljgdfrvfiiampsuawxpsoosedtnnjwtdkwoykbukipvsvyefwkmlkrezsglrjnvafyyvbirnjkqgcobuhnwumbjwuyuoluyjmihghzlbrkkjewnobcuwopkdvokmqqwkpesgkgqowcxglywloojdjfhzeoihselaabpghovbwgaxwpdonuthapdunjpqldjkzovybxpzomvviutgljkpbdimbmanzyyzghlnwohqpjxupzrrhcrqzqhiupkinhjoniwoyxlgadvdlqnfwjucdcvvzmezbsqtcotbrmmjtlaihilpccrpszratqghwktpzciqexyqrbxnzfjbevsucqhmaaaedekipvhlbpscrwjwkzyodhssywlikjfmdbceehcvrhkdjxtvgtqmomaraninjzhvwzdteirgubbpochqocexfqxnqmqngezpedgpsiltsramrukxshrfhnuvsxafjfgkmqyapytiaeujczucwceyecjjbgbdmoavohqovlsunwbglroncvekqqbkuijehjbnyteoaegycbygfkfekkqnqcrktbbaksrcgyqmqnrttmhpefhzlmvoajypyrdchmyibgfbjgumrdfchliqdjjmoztvchtdzckjyzwyvfvabscxgymxosfstoagmvpvdofemlfzfkvexwrphbfxfsgumjvkisvvrpjztcxuhzqjwoatzqyiwjsvoismgadkxnejpbzhdymjbgejoboelmdpspqisukmzdytpqzbzpdhtyruutllgsipecruztupxjxnpgbcgtbhhkwcpcscjeebjzaxambflggzdhaupwjsswizkabaapecazfohbesowsyttexkqlayvnghvpcrhglqioufwxdhyqiyeedfioepddqmqzgvbvnkdbkkjujwrlfuxjfbuhicxnanjghbtnfdfxrcxdrqadmbpascwccifcpubjarrnzwtpglzowwekotstiwxlzyiesiqtbhoelbugxricrngzpxdarztndqnwtztoexcfsfffybkztsiwzarvzxesxrioahfheolpqneizdobicukwymgajilvdbxjbzzzqrjcoihgjlofofkxsbfmztousxolyfynxttrfhurvacvuqmvdmvdpvjefvwnmvcjqfleifbgntlwhynrqprngfcahzayyxrpunwtqmzczmigqpmmfyvvqciskpjxmimbdtttzfimioenelferxtcudmalkbqojuyrptrcrcgokjzromzeeyuznjprormpqtkjrzuwncumgrtpruqpvuiaseftkzhqdcywcovjytkvxkutknlymoiwknogudokqmwvmkqcxbyafpnmderopxihtuvtacnmkshhskozpysvfinvkseyhhdycmvcqmxaqbhbvzsdzlguqquqcabykcsqaeefmvgfmevsnukwrytcdxnmvpbfqekcjmccqfqswmotyxeezypgarndmalaagviyyenfruxcnwqtgyxifstfgbsdmlwtxmkoahobzemdrbwccufimsktsaluysyigwaveuezhfuqniciriejhwrgdzuvtducvkydelsfthgxizobpfciquywfqhhpsthfipenbotvizyqrvtfhkzvepscmfauhctmkhhyjjrmusjdwfuynghbwaorifkffnetqehbkapoqojkkubfxoisdouzqxejadzulqfquzmlaretcrrcjscjklfufuizrtvosthcecivbogxllpxzoihiirvderqkxhekqxaelgvippqonvwsifzoytfennzidgwmrppdlwwfcvuszmsmmqsftuhnauohniuftzbabhwdekllsszmloqjosdmptpuusnnzkrrxdyccjoxyoavkgdwbwkliaotzjlesbiahathesagnlrfezqorgyukasxnlnqlmcfokqztpcczlsvytwmrphmceyqtnvntwmmljfisyiszhacfyhrikvbkejblryhfgdwumwzstpzcgptphqmqqnfttuqjshcmmzfkopbqalbxjrscbefblkuhbzmnodgajzoqnkhzwsfhpvgokcyaqqybcwbqyrpdzqdtfiayvophivvfwgkigcqttxpigpqxvyvtfkmdgsdijxihcyiykdhxiyepcoxkpjirsdeezsjlogbguvshcasuvvpyrybcuvqbqtaddveyndsnrjdffszzhvknbsrcaeouyfqggpxzutgoxmkanvzkztnelncpxsjcimfoefqivpqrfvkgitwwwqtqisozoxuxheaumhntikfzlgvojnecympqdnbeghyktnzbbpcpfdqfnyihjchqtmgouwoevkylhzyxmmkoiywopdwfueznukqgxdxvgvqlxmptdszochifankbozlktpmstvllvkqytxywteiidxtvpdwurzuosonvmxjqgjteqmclsjxklopeiysjqjlkvabdqtmuvlalchllobcjxcxeicnvmgttkhxabkfxppktmptczytukbzmwymwmchawbohkqtajgiwbmlhvivmhdeeonngvcbgcsppbxeiooilgelxxuudkjxzzugcletjdtznqpzdalpzfhqzyrntljbnsbfpeeqvgpsrykunsmjjasnxmvmavuemnnvxcobjzvfvygzbdzyzrgxpqvarkwtlsbuiksjgsbhcneytfylsrokpcgjahljzfwusmlwydfhvqbjwdckzowqdhtgmtswsemghxhwlycaheudikfjfmpnuvfxrhfjjyeregrejcfcibtjjxnsyeohuhurrxyakklddbbruzxmjmbyhyrzqcjdazkvjdhebkfchywyqevqgpkwrfiwtssqvbzyovhaagqeekjcbzznziyymrlpbzclvttzwcpesswxvwknzpqdnzcfwwdanrvsgpfxakgchrkkguerurekcumuhlhoxhcddsvmxpnmkfddjcepsjnlxgqaqtmllpindndwwavcthnujkzfdkctnomipuctconyajkfvpwjjcwprzrzpjetmjwgumaxlriijkuanmqpuqlfofjdqxizbpdmphnavmsibtwsgpgtzqlxcldejedwigopiahgttqffdgyigxmmoinxjwsuljhtsjaifvcapgoxazoondpyvrdfodfqkuckyibcxykcxrzoxdxkwgjuafyshxaaofjxnftgjlswgtkbzyxxgawhrgliabdncnsfvmcuszkgtiogafcvtpssiqctlmaccvkqroobmnmirmtwhgcwxxuxghorsjauqkxjewjdbfamcgkakjlsryvawhsniuksmicjscbgcliccjrinjwtnghnecdpgjbkscuzrcvvdgigdrqmqocgwfxmosbpjwbjjafdnovgxhetphpydyogxuqyxxxqmyentbagcgfkufrbzqmzdljfhqxfdlrhvnavpouoeltrggaqvxaegboljjcladscdiddqihbzukbfcjgqahxlzvweqkokbpffhalieatflejpxstoseqossdrsbflrjolsksrboyewyxkvyodykugxinhgpcmqnzhlymvjmiybncvsvpvzldlytvhtqzocqugzvlrsuxnrkscscfvkpplovcikigyopogwojvwnxhguzxzrqjyduwpsojsimhogzhfmstjjyvsdnycpkjgynelbyszwddycgypflqkkobkyvxeccfcgixhoifxuehagwdkzztanhdivlsntppgcdajyyuhrtipsduanwkagmhcteousrweavrwqnncmxgdghjpcwjtaokhudyzxrxhnqwslgpoemjopsbjmuvtmfbyniuxskwuzdadvwueiohacxmfuddkkttddrqiiwsujeaeodbzguuddyzwnpycfknuojjdwayqyttpbsuqlyvbrgidmpzjnqbkagofrijikrittaxtiqqbwvtrnqutmzjfnqkashbdtisnfffihniknqeblchemzwsfhjoiotjmuolyprdfpidfpeutllwtavcdoreitatpdjififpfobnrhkowzjnbdoselynbewxagtzbetyriooufnpgjnzirjutvestaxbudtfwtlmhokedkuntejcyyzmhyeveyixyahwwmohmtuwvosqiiwokkyyiqdfiuqrylczllgbrmjpydskjblztygxgpeqfiikbsvrrmfmjjyjnmmcshmkhywnztmymcrsgpqmcvlypuydtrnyjxrlnjzkcwlzzvougctjsnzrdhqakyftwbybljakdsfmsexaxaxksvbqqvaegfestqfdsoaofaggyfhvkvhlvcbgtwdmnuwthivinencppqwxaojabpydxlcfblgysglnjoqkzywfwetjjshordjpfxawoupqpjtirmzylmpleuonnveqdtwzekqakrobsxbxqwildpuvkmlogtzzhwvuoztkspxekuvrqwzbzdzhjozqosnvmrucnspeorbrwlgbrqljqgmkuedgcjptzykyzmovpungwinhmrysehreebjtkafbglmrauhympjkarcyyldmzhkvjnkrtzdhhvtqoywsrbfiwswwzapmkbyewkbcujbyyxifbzigxsfoteelpywbjdfzvcnuwybbgndnbuenozmlpawibxklhgmcoodwipjettuhutambkyevapbhhumjhqfakarskfmjjpigrjsxlqhixovzdefqxymgnwcovfifjvubjaxoxtqmaidhtaqcsqggwxwjcsqqhlqysswpezaoarjssligvnccvbuejjbkwzxaikkcsrqmrdvmskgopzqlpxdouzuhsokcbweuwrzqcuqjxewhpmkrafivzurajyzlgsstlssdhfnjmjotyjqbnsjnfcvsptejrzicswkzvmhwumtprzhdxzqxjlnkgmociveqqrngydipsghrmntqymmqmwxrlovgxtepxfxlojwpmlzmenslyljtptkndyrjuikjrrurazgwgjginlfyuwmkogriokpxhbablkdwwnxxpjokfnlimmbeausuukteotoypwakqzeborvfwiolyvvxniukzwfzvubuvayzkhldwmbzpwjzmooryyxotosaaaecoivyqvqzqrylfdugcubmasktfpxpsvkqrqntipxlqpbjgpjootfvxbycvdolnrmcgvdkyjlyqjgozirijcwafdajnrokkubafhujulkfmqsewbllzqhkutsardfvkhswcpflausmcgjlhgskdsoppylvgulxvuquaehvssuoxfgqvidlmmocmbuhmzpmetmoewsokxpcnybnrmkpjxgebuydnftzxunbdmpqvttmpfziolhaoezdwhcrgsusxmgqgstwyojzwqtfnqvyjeihzpzjhzvhpffdnxejipduvvhwabolklhkgqoyqfupepibhjtnylnoivjfguohjlvtrxnjuqhhynebewhsmahwpqlpftmnvmjuaubcnunggqmwszhrhehpesvviafoxlmnvhdjcokoizxdtehtlxpucjyncistahijvmletwghdehijbxgqucdznemeexaxgkokqtpbhhlqxntxsflixprpwhkaubfiejpvcnavbopiezsfsdbaoeofrqzlneffagotrzvlkfwzlvncjglfcjxdxajggcqvceaobzdsmrcsrxjkxablpnmwodbvdwahnvsoxbiyayzerffyprleaurqqnuldoojygdufoqxgpnvdnwmbwllukunjtqxwyhsrqwwmtkgyclgbllxogtvjerxwhyrojvrulnklkixknnmgbmszxulhyykhhacfckkoplddkkbzaukxpdumdiodrswbomdlzdiifatlupwvlikgvhxczjfkrsuafrlorweihjgnpyuenavkpykgbavsfktiiqpclfuvtcotwztqprwjfimrsqocjpjditxjsueslhdduqrguwybzkchgiroqchlrosjwcjucfhhorckvcfoesztzthmxyeupmyrtkwsaoouhmzsufrtycbufjjsdqmmfkldqagajdmpyrwrfkvxgldmgojomwcinwhssttfxyrngqdeoqxucukowmskdmrsruegekxdbrnmhuegngcqxzvmoypplxqgsfivquhfnkxsxqnczhiuflwnmigstdnavsxvvvuvxzmjizyvybvqevjdklmmohsmywgjvonqreydevnioygjmzanipawurjotdvpkaevviyvvqpqrzydqygcazvrwugnzhhclaibjgsvwglzgxfaqrdmzqoblitmsbbjwfltnusrpyupgcbrrtbuqgxylnuobrldpzxirbgkbvsmhavdhmfbpbdzwqtqaqbezjovitosmgyatluomurdzchrtihtmoegzxppaworfoinixhytalzhhxlwvbgzujfgfwjldpwtzlzunobgylqrncyvzbsixbytwffodqjyxnofydjmtvnlmovvrfduguzfldsvwwcrmgtqsmjlfatxsfjzgxdxleowodnovisqywbwpufltlzjlayxkfiuvkztdiafjhudwsvnjitziacoeyysukccvnjyqwrltbbclnyagfjbnukqpdpltyiesbzhmueyrwpontbreoigznxdexiqbfbiietnisupsmvicxknbirlydwpyntpuwmsfmkrmpzrlcmgnddsvnmfisokxfuirptbyioexvinhnxbnkuyabirdgbksfwenrycvpijtlrgsipgzcdboiqucqsrotwceqoscccttorsboixxpbkvxefcwxqcndfwthnbfdqkagzxcgrtykccrtvjocomxksgfvaplxmnmqxpclduuvmbawppnngiotplzfevrenbqjsubzaelsqhvkditlmcrokwbbhvhwkjnbcbehwukixwapkxxnxfweqmjbwozdbgbjvrdjvcdywxsfkdidpybqyluwtulkiohtvcnmbiqkwaivoahykztaioxdptyzdvlyrqpqcyrvdxvarkgzavsmqsqoyrpgbaezlaizrcjqdvzdqtnlolkvivbnhdmgcxgsshwkutdtzybbaajaxfcgzuukfajnjlpppypbqokctsrakdnqpkrqmkriwjcuvohidahrtrhhwrvktnbkubvuarfbnicneqylpzztsrcyeixvbtrtulzmhrzgsyicqpuaygszlhjfrhoqmuuuokokfvkqwuybctjnnyjcaazswajpdrrzpdcshvvzdudclbtbmgnghbagcaetwolegcjunmhoejnwfpgcudwvqzatvwdjnmppdrwhfxivolidkqghlwhevqyeeanookdbmjjywvecepwmsjlymkwvpxspibxjzgyqowowiaisinfqfcppfnniaqxbuywulcqtgktssixggzbhdlxarsjygjocsjkxirhlcqjhlhgacuxxdmrqrcagyqxktpuryxyczeghsxsikqnvuwnttnjylzxobxiblesdlzsadasfiufvtvpihgfvupuxctmxgteszzorodcdfrvvgbxjljgbxpoaenoofvkyyltfipddwxinawdszinxaeevgdhtkndnifjnvfduhzxhgckayrljpzdaqdjebxhjglrtcbspmfyejytbumftarlqqywiquybqwjzgubkloqtuwekrkdvjvzxbzdawbapnduxrexmqffkpbmwrzmxpyftkooiuhzqzepvjfzpubfffluepcorcyaklidaiqggvyqiqdyhhrdisraftvmefzxrxukmdkzzevwowvvpixswrovgyuxrvqewspesfqxacajyqvsbnbfhbxuerjzvpmqvsxolfqsqxfmezfhqptnreuxfhnzxmgylfllzopvrlvsrghwcwpdihmtcfyyextjvzcxdfqtklifzdeusjbvounkthxxwhriutmroplcmtpsmbvcqzusejiciatpqsfxqqhunlksdfqvwbgrgezcvgpiqcmtgkuzqsejuihajgxlojeylpnfswwxbtawmtnujybesbdkbirnrdnjwmpmcufpupumfqfckvpoikmrhgcpigbnrraqceqttqxgawlkpngqvqclqbaznnyowgczpmctvpgyfromviulyojygqoswrwlrmzrpbcjeqnawaxqbolaqufbomrljaiafsfkrgpzszzskqmtcdhokteeuduvwlcnhdltalnrxihyjwyvdwtqxpgszygzcmnfcuwmqrdlxcfbyigayuwfgyxuddcdyrpinhihkboysyfnbgjveictgmiuaydbpikfhaxhwtqxhqxldxlopdheggjyrhfxyuibjxonbdrzdetzfqwdrbalnvtcjcmpvekxctqiceuztktyxdwpuokuuqmdjqzejwhmxtjfeukeaucyafoqkoirweonjjgvdqibqbgngdaamnivomhajsnronalruppsyxxfyeqjvfrtwbeusepthjiatatuqzrdlqepqflbbrvwqkoeaomviqedsphrabmxamxdbogptvarwfrvunitolfyjhmwebmtvwmshxmyfgctvkcziaojmqrzgpfunkvanhazchxlwkkzqkcygnrqnnsmenmyzwxouaalwxuwggbvyhdgijfwaqrrodreltjguejgsfppklwzirzsmalbdmcntrrfzvstsqiuzypgtowutqlphsovjxbuqhjmvtsztqfkfpntoztovadhyekpwcehrawhqafvucldevctklvjtextviyirtppkysjoqsgympgyvozrqiwfxzyrpresisbcskjhafhqzfflgaaiyxqwlwdggukkqjdwquynrjhfdudamhtetzgpcjcwtqmttdjyyfmbifjhugsijmkidrvhovvjkwhwqvzrdyzygbhjjueyzrdlfdcbhatvwtvnqpmnvfanjdydxwzcwvuptswhxvhivazcliiiykmvlhqbgqhveklurcwvrtalohuydnvmajexultfoqgxjmcorumsbutlbryilkrxgerhgccdzijpsyvwhvbduhnckozbsakpqlenptrigxeqqwqzzwqnjhyelztzlrursohxwhxfagxauzzywzdgtpdwbxndrxcvildtmftybitwlykbrvhpqwvwqdqzjbrwpbhxhopxzmjhwegbdclywaaidrguuzxthgntrkbxrbobterundhzddevsclkygaumdeafnfheumpzhvkiyaxkfpaikjzpiveukjhhptjvwppsexbyjvkbaiyvegbrzivzrpzpjrnfznjkonadraylahanfrscphmhzazpranzbyfzvrocnadbzpdmccvpkdqhfnblubmwapdgxvqwveocfbrfoarjkqyqwypfczlclzbnstwbfbmkcuvbbakhfhibytutpgxagvyvusvgtudhxtjkmgonjwlumqkbxpbnkmkmeeufpjcsdkkhfxadhykslduwchjjmmkrhzwhnvzrabtyqbisitowvpvmatbjykmozwlxqzzikzrivueboujhftrjlyqqytgarrfjjackuwtffilqzkmwpdcucccixafnydlicivadiwthsfehidckoexajvubqxeusfwqtebieoyvlrsmvttjmfidnktnjshvagpxclfudqpmoruenmsaipqsaoukmxoxdheasupjvagpznnjpkugvahlyokrgkpsaexlxjzjislhywlbpbtvtviiavgpclddnnpttyhrqixqojlwhialyfchlwzoeeaurrijftbmexifoolldnbdttnvuxmcjwgjgrxlehiporcmqfjasllvzykmcpkdbbcauyxmtbnwdzyzwzeidxncaqyorganedpxowjxcoyqbsuekkcavfggqbrfxgrcaqmelwodoxzirvwslonuqihdxyymrmewxufeqwfwhiulgznxfbmeimftsvcpotmtsynhfbqnknjwggwtqceviikbebcwcwqllfzcjiiosisbfrzilwynbvngahyljcckksktbqpgokiqinxaatckwvseihmbpofdqhrwmcclbnskfofydwtujiunlodasbvtmautgelnsephvuhmfcsxjndwzaupadwaertpxmqjvmzbnjeeyqgkttdjqgmbennhiudlxxzkqnomgytuntrmpzaqtfjqapbxmuenynknllhokuqclgspfxaicgqckvethhgvpkyusmeliulquhjzshgleuanttzvwlekvtwdqvvggwhgfwnkppagjbngfgbmxgogpkkkfhfdlbneemvvfhghuqtriovqtbylmzrwwhpsbxsstyqsuvkdvnvrrgsjmdqltznobotlqzocjaciecasgkjxbdwitbxhvledpcyjrytppduneivcaehsfpyrlirprgyeprslsizhyuzvzrqcxltyslydethcsercwgojhbrymzsvdldedhorubbhdoedksyaxkygpqaooofvgoqyziijimrivfmvpdpeawdykbxtstqfvnczgwjbvstairchhtczhcqlpkldczlhetflhdccuhkkfvbxfuomhaqbjsesqegwixwsidvzrmqadyortgxfxcqfgmxkspytkqfwvxrhlxudmmwrwmrbnutdjtzvjspcunxshcukgwjppaaewgtkrqatzjzkybhvpnuzncxzlncmbsccumqjgwwgrgufclsftqqqaszekqbivboitgnqmvekkqtrkrbzftargtjjbxsujhhxzhppilpoczgdwncudjfakdsmgvqtvcarxstftqqvibrepylsadrmavmjzksuhyfswkpiqeehrrrtsjwvveibpuuiqauvpsjzfphrrbrwqpufanqodrxcrycchzjgshvrmfvezxlpabswurgmybjsppasuwffibctmzrtzvjlegvtctgcudhrggiqfdzwivgzasbrckrqxztfmsavfnrabnwwkpwybyhrnxgecbdeelfhzoblwtpxzokxhnucwzemwuoqpmlxxzroejnbpyjweimvrwhksmvpaegzfriblojsfsughbsuahobhbiifnoamhacvjooocfwashsisuswrtflovjeqzwmgquimawljzplrqkqtsqhhnbnmzbyjeapuqbkbsxmlzzlfystovsvuadbbrwvwzttwyrkuosqotxnosypynmncyszwqnutjgrwiacvhpxkzkasyeccndwgivqcryqvnhabqxmevtrvhbrvktbwvehjhomcijmetfwvkiufxlivsrtlincwhxcfxvdtzudvntwgptujsxfarpbcschirbvqanybullkeglpqlwlkbgdpvcckutamtqaaqmaltijafgrdiqqrcjqzalakkslawvafechvyjbshnhdpqhbelkguecpcpcqayregfbrzcvmkzlncuvtqbblnbajihdfaurmslkgxmlhcpcyopgzdbjwnjfgjprtzcxdtbntjtdgzperhtqejdodejqoklgpnixcegximpfmklrvsuoyzwdjoapjroalbgcctorplbzxnmbeprxghmlebosmiqciimcizxmxsxcemwbaivqyqpprpsytoykurnptoapwwwxmxcngilvauocoflnderjzgtsbsmgdpxjtpktocdwapnmorlkdxejlqiieeuhlipdfspbnywvhjhskehjenzcxminfpyvfbuscqitrvvmggotvpdxqpjnwektqrmxhuwvookxxamwqfaglrtsxfamzlmtmfhmkdnnwaeqlmmiacedtiabnhqmasmvqgqqhyokorakgsrbkovggghjxvmmszypwtdxacryttzmntzzhrozpncyomwejjsdvqpnkducrpkvgjddoyfxldpdphvofcqhnsifoequdgbcfaweemyjhuynfmxraloocvtopntieetsarmxxgrueocagfelbhevltedxgicdexxvohqoeigmgswdznjlxfdkxxtdnlhjmwbtvjxdgmvmutrxpsdxadodngwwcmnvkobkxrllevlydqrycevosjehrxiblnanixvfuqibjtldtqhuyepapgkewyhjxtrsgmvybigtgqvqhhodzcpsvawpmckcjnuydcvfabciicqqkqldxgbgerwuxegdeiltjukctwolgspbkgindoibxvtsvfgmievtfzlxyxieerracaopiqvknexevvwqvobzxcqyfiyhcucpvreuuphlmaahhfyijdsszqttpnobzacggifhedlypnrzvkidjilmecrgbjtlelivvysxkmilwkyjyfcogkogigfzmqriqzehdohvjqcfltmatzdbxwygfqmnvklbjlzijmeawrlwmiilhxeiuyabuqhbxljgebeiuxjngvmjvvgmgutgqhjubhdmeurkahmpxyxadpxkdetirtnnjiwylusazcjlvgttxkrklrxroiribihnmaiorreqcaolhhvixkveqzoyiyskamagjfbpvfxnflsgrnykgcpfzhgepaouynjxmifcioqluxwzwpmtjprkesvxuvtnoklwljbpucwzruqhxtvipbjdbsinwxeghxyspnaodgcqkgoatocqqpxqxmwliqngjamryzbayfqbgjtpxoehhtuvtrrtphignupyalifnpflttcdildohkmwtohxckhnwejonlzozbsejdtzfvxkoxsxckbwvdgtcxoregmhahnuptgvsoiyjbmbcgjwjluadppzpqyctnqvwaecrpujxtourfiihvrhmmgrcapyeyndlkysnyyztpihpjyubuhzztzbrlkqnoowzrsumuqkqsigodofwtjyyhrjrinfbzrhbqkbiuyruftsgxvithmbdqwrkktpkpqxbqidaqeydydrdkqiizwkyhuzksfwiwoznnxeciivnfiowgzovtlmgwryxebkfunnbmpzuornqlemqrugzrpvqxykrfvlihxgexlsaipgicgmwqajagmbxdbfkwlxssqlcyuhwzmnzvlspufgkilutcirhlagdmthtjmkbjvbjwyzntfhmkbtpuejwbmymfqbuebhhwkseijlaqaejrmptvtryktsthepxsoofjimjxtacfaxttqhcoiebwytwxwsibeecwhgcjjvoukksphgqptneuqmhvrjewlouephrcnriejanwcjvchteskafqkgmbqxqyzjikslkpzjmaqfhzmkakonpeatytfyyncslnflvivvxclv", 492153482, {23,20,4,11,4,24,13,25,12,21,17,7,6,21,12,11,22,25,22,16,19,8,16,18,19,16}},


    };

    for (auto& [fst, scd, thr]: tests) {
        const auto res {lengthAfterTransformations(fst, scd, thr)};

        cout << "RES: " << res << endl;
    }
    return 1;
}